### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by jeremiehuchet** [diosmosis/terraform-provider-docker-image#1]
Your repository is missing a license.

I wrote a PKGBUILD for Arch User Repository but I can't publish it until i know the license you chose.

**Comment by diosmosis** [comment]
Added an unlicense, this code is in the public domain. Feel free to use it, but I think someone that looked at this created something better. This one I think: https://github.com/gstruct/terraform-provider-dockermachine

**Comment by diosmosis** [comment]
Or this: https://github.com/gstruct/terraform-provider-dockerclient
